services:
  nginx:
    image: nginx:stable
    volumes:
      - ./certs/server:/etc/nginx/certs
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8443:443"
    networks:
      - mtls

  go-uptime:
    image: jniltinho/go-uptime:v7.0.0
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - ./certs/client:/certs
    environment:
      - GO_UPTIME_CONFIG_PATH=/config
    networks:
      - mtls

networks:
  mtls:
