// Part of go-uptime, derived from Gatus by TwiN (Apache-2.0); files that existed in Gatus were modified. See NOTICE.

// Package static embeds the built frontend (web/static, generated by make frontend-build) into the binary.
package static

import "embed"

var (
	// FileSystem is the embedded file system; every file lives under RootPath.
	//go:embed static
	FileSystem embed.FS
)

const (
	// RootPath is the directory of the embedded files, and IndexPath the template of the single-page application inside it.
	RootPath  = "static"
	IndexPath = RootPath + "/index.html"
)
